# ---------------- #
#   Main Configs   #
# ---------------- #
url: https://ttcoder.com
title: 头秃程序猿 — 前端知识学习分享
subtitle: "不想当全栈的程序猿，不是个好前端！"
description: "专注前端开发学习分享，程序员升职技巧，防脱指南"
favicon: favicon.png # Image must be in assets/images
name: ttcoder
encoding: "utf-8"

# ---------------- #
#      Author      #
# ---------------- #
author: Liang Qi
email: im@ttcoder.com
location: Beijing, China
timezone: Asia/Shanghai
company: 
company_url: 
github_url: https://github.com/ttcoder404
github_username: ttcoder404
repository: ttcoder404/ttcoder404.github.io

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  enable_coderay: true

highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/

source:      .
destination: ./_site
quiet:    false
defaults: []

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
collections:
    talk:
        output: true
        permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: 'page:num'


# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-06-05
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: false

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: ttcoder404
    repo: blog-comments
    oauth:
        client_id: 0f1df03507262b92fd0e
        client_secret: 08cb3c71e4bd1aad2087b35962258d7eb284c543
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: ttcoder404
    repo: blog-comments
    clientID: 0f1df03507262b92fd0e
    clientSecret: 08cb3c71e4bd1aad2087b35962258d7eb284c543
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false


# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /talk
    label: Talk

  -
    href: /archives
    label: Archive

  -
    href: /about
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        content_header: true
        content_footer: false


# For about.html. Fell free to create your own!
skill_software_keywords: [C#, Python, MySQL, PL/SQL, ETL]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, VueJs, NodeJS, ExpressJS, Webpack, elementUI, iView, axios ]
skill_mobile_app_keywords: [iOS, Object-C, Sketch UI Desgin]

twitter: https://twitter.com/ttcoder
weibo: https://weibo.com/ttcoder
bilibili: https://space.bilibili.com/160394977
zhihu: https://www.zhihu.com/people/tt_coder
juejin: https://juejin.im/user/5ec65be36fb9a047e16c77b0
jianshu: https://www.jianshu.com/u/8fcf5a4463fe
v2ex: https://v2ex.com/member/ttcoder
steam: https://steamcommunity.com/id/ttcoder